"""
transformer_builder.py

Reads data/pipeline/raw/trafo-data.xlsx and produces:
  data/pipeline/canonical/transformers.csv        — canonical transformer table
  data/pipeline/pypsa-components/transformers.csv — PyPSA-ready (name as index)

x_pu values and the r_pu default are loaded from
data/pipeline/x_pu_search/x_pu_lookup.json (generated by
data/pipeline/x_pu_search/trafo-x_pu-search.py — see that file for
sources and per-unit convention).

PyPSA Transformer attribute reference:
    https://docs.pypsa.org/latest/user-guide/components/transformers/

Run:
    python src/transformer_builder.py
"""

import json
import re
from pathlib import Path

import pandas as pd

# ── Paths ──────────────────────────────────────────────────────────────────
ROOT          = Path(__file__).parent.parent
PIPELINE_DIR  = ROOT / "data" / "pipeline"
RAW_PATH      = PIPELINE_DIR / "raw" / "trafo-data.xlsx"
X_PU_PATH     = PIPELINE_DIR / "x_pu_search" / "x_pu_lookup.json"
CANONICAL_DIR = PIPELINE_DIR / "canonical"
PYPSA_DIR     = PIPELINE_DIR / "pypsa-components"


# ── Helpers ────────────────────────────────────────────────────────────────

def _parse_voltage(bus: str) -> int | None:
    """Extract kV integer from a bus name like 'Barapukuria_230kV' -> 230."""
    m = re.search(r'(\d+(?:\.\d+)?)kV', str(bus))
    if not m:
        return None
    v = float(m.group(1))
    return int(v) if v == int(v) else v  # type: ignore[return-value]


def _load_x_pu_lookup() -> tuple[dict[tuple[int, int, int], float], float]:
    payload = json.loads(X_PU_PATH.read_text())
    table: dict[tuple[int, int, int], float] = {}
    for key, val in payload["x_pu_by_combo"].items():
        v_hv, v_lv, s = key.split("_")
        table[(int(v_hv), int(v_lv), int(s))] = float(val)
    return table, float(payload["r_pu_default"])


# ── Processing ─────────────────────────────────────────────────────────────

def process_raw_data(path: Path) -> tuple[pd.DataFrame, dict]:
    """
    Returns (data_df, warnings).

    Detects the PyPSA attribute header row by scanning for the row that
    contains 'name', 'bus0', 'bus1'. Same trick as load_builder.py /
    generator_builder.py, so insertions/reorderings above the header row
    don't break parsing.
    """
    warnings: dict[str, list[str]] = {
        "missing_voltage": [],
        "missing_x_pu":    [],
    }

    raw = pd.read_excel(path, sheet_name=0, header=None, dtype=str)

    pypsa_row_idx = None
    for i, row in raw.iterrows():
        cells = row.fillna("").astype(str).str.strip().tolist()
        if "name" in cells and "bus0" in cells and "bus1" in cells:
            pypsa_row_idx = i
            break
    if pypsa_row_idx is None:
        raise ValueError(f"Could not find PyPSA header row in {path}")

    pypsa_names  = raw.iloc[pypsa_row_idx].fillna("").astype(str).str.strip().tolist()
    human_labels = raw.iloc[pypsa_row_idx - 1].fillna("").astype(str).str.strip().tolist()

    def _make_col(pypsa: str, human: str) -> str | None:
        if pypsa:
            return pypsa
        if human:
            return re.sub(r'\W+', '_', human.lower()).strip('_')
        return None

    cols = [_make_col(p, h) for p, h in zip(pypsa_names, human_labels)]

    data = raw.iloc[pypsa_row_idx + 1:].reset_index(drop=True)
    data.columns = cols
    data = data.loc[:, [c for c in cols if c is not None]].copy()

    data = data[data["name"].notna()].copy()
    data = data[data["name"].str.strip() != "name"].copy()
    data["name"] = data["name"].str.strip()
    data["bus0"] = data["bus0"].str.strip()
    data["bus1"] = data["bus1"].str.strip()
    data["s_nom"] = pd.to_numeric(data["s_nom"], errors="coerce")

    # Parse voltages from bus names
    data["v_hv"] = data["bus0"].apply(_parse_voltage)
    data["v_lv"] = data["bus1"].apply(_parse_voltage)

    # Look up x_pu by (v_hv, v_lv, s_nom); r_pu = default for all rows.
    # Raw r/x columns are 100 % NaN (plus one literal "typical"), so they're
    # discarded after parsing.
    x_pu_lookup, r_pu_default = _load_x_pu_lookup()

    def _lookup_x_pu(row) -> float | None:
        if pd.isna(row["v_hv"]) or pd.isna(row["v_lv"]) or pd.isna(row["s_nom"]):
            warnings["missing_voltage"].append(row["name"])
            return None
        key = (int(row["v_hv"]), int(row["v_lv"]), int(row["s_nom"]))
        if key not in x_pu_lookup:
            warnings["missing_x_pu"].append(f"{row['name']} (key={key})")
            return None
        return x_pu_lookup[key]

    data["x_pu"] = data.apply(_lookup_x_pu, axis=1)
    data["r_pu"] = r_pu_default

    data = data.drop(columns=[c for c in ("r", "x") if c in data.columns])
    return data, warnings


# ── Output ─────────────────────────────────────────────────────────────────

def _print_warnings(warnings: dict) -> None:
    sections = [
        ("missing_voltage", "transformers with unparseable bus voltages"),
        ("missing_x_pu",    "transformers with no x_pu lookup match"),
    ]
    any_warnings = False
    for key, label in sections:
        items = warnings[key]
        if not items:
            continue
        any_warnings = True
        print(f"\n  !!  {len(items)} {label}:")
        for item in items:
            print(f"       {item}")
    if not any_warnings:
        print("\n  OK  No warnings.")


def main() -> None:
    CANONICAL_DIR.mkdir(parents=True, exist_ok=True)
    PYPSA_DIR.mkdir(parents=True, exist_ok=True)

    data, warnings = process_raw_data(RAW_PATH)

    dups = data["name"][data["name"].duplicated()].tolist()
    if dups:
        raise ValueError(f"Duplicate transformer names: {dups}")

    # ── Canonical output ──────────────────────────────────────────────────
    canonical = data[[
        "name", "bus0", "bus1", "v_hv", "v_lv", "s_nom", "r_pu", "x_pu",
    ]].rename(columns={
        "bus0":  "bus_hv",
        "bus1":  "bus_lv",
        "s_nom": "s_nom_mva",
    })
    canonical.to_csv(CANONICAL_DIR / "transformers.csv", index=False)

    # ── PyPSA-ready output ────────────────────────────────────────────────
    # Columns per PyPSA Transformer spec: bus0, bus1, s_nom (MVA), x, r
    # (both per-unit on s_nom base), tap_ratio. Omitting `type` keeps the
    # default empty string so our x/r are not overridden by a standard type.
    pypsa = data.copy()
    pypsa["tap_ratio"] = 1.0
    pypsa_out = (
        pypsa.set_index("name")
             [["bus0", "bus1", "s_nom", "x_pu", "r_pu", "tap_ratio"]]
             .rename(columns={"x_pu": "x", "r_pu": "r"})
    )
    pypsa_out.to_csv(PYPSA_DIR / "transformers.csv")

    # ── Summary ───────────────────────────────────────────────────────────
    print("=" * 60)
    print("Processing summary")
    print("=" * 60)
    print(f"\n  Total transformers : {len(data)}")

    print("\n  By voltage pair:")
    for (v_hv, v_lv), n in data.groupby(["v_hv", "v_lv"]).size().items():
        print(f"    {v_hv:>3}/{v_lv:<3} kV   {n:>3}")

    print("\n  By s_nom (MVA):")
    for s, n in data["s_nom"].value_counts().sort_index().items():
        print(f"    {s:>5.0f}        {n:>3}")

    _print_warnings(warnings)

    print(f"\n  Written -> data/pipeline/canonical/transformers.csv")
    print(f"  Written -> data/pipeline/pypsa-components/transformers.csv")
    print("\nDone.")


if __name__ == "__main__":
    main()
